### ISSUE TITLE
Theme contrast is off

### ISSUE THREAD

**Issue by PaulRBerg** [FuelLabs/fuel-graphql-docs#22]
I can barely see the titles:

<img width="600" alt="Screenshot 2023-09-11 at 12 57 21 PM" src="https://github.com/FuelLabs/fuel-graphql-docs/assets/8782666/115bd5f5-4e62-4862-b6c3-e1e1a0ea62df">

**Comment by calldelegation** [comment]
https://graphql-docs.fuel.network/ Looks fine to me @PaulRBerg what browser are you using?

**Comment by PaulRBerg** [comment]
Looking fine now on my end, too. Might have been a temporary glitch?
